name = "my-website"
main = "index.html"
compatibility_date = "2024-01-01"

[site]
bucket = "./"       # ç½‘ç«™æ–‡ä»¶æ‰€åœ¨ç›®å½•
entry-point = "./"  # å…¥å£ç›®å½•

pages_build_output_dir = "ä½ çš„ç½‘ç«™ç›®å½•å"  # ğŸ‘ˆ æ–°å¢è¿™è¡Œ
name = "my-website"
main = "index.html"
